### ISSUE TITLE
Make the axis labels more widely spaced in the plot functions of views.py

### ISSUE THREAD

**Issue by paultgriffiths** [Vese-Manch/Python-intermediate-rivercatchment#14]
E.g. in the plot routine, could space out the date labels, or supply an option for the range of dates to plot, and the frequency of axis labels. via https://github.com/Vese-Manch/Python-intermediate-rivercatchment/blob/53fe8860174dddb123524aac1d8d49f6d7b0b0d2/catchment/views.py#LL16C5-L23

**Comment by edwardghbaker** [comment]
I have rotated the xticks to make it readable
